import type { Metadata } from "next";
import { Host_Grotesk } from "next/font/google";
import "./globals.css";

const geistSans = Host_Grotesk({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nest",
  description: "Generated by giga",
};
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          antialiased
        `}
      >
        <main
          className="   relative       h-screen
         lg:bg-[url('/bg.png')]
           bg-[url('/bg-mobile.png')]
          bg-no-repeat
          bg-cover
          bg-center"
        >
          {children}
        </main>
      </body>
    </html>
  );
}
